name: llvm
description: Dart bindings to the LLVM C-API
version: 0.0.1
repository: https://github.com/monki1/llvm_dart


environment:
  sdk: '^3.3.3'

dependencies:
  ffi: ^2.1.2
  meta: ^1.14.0


dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.4
